### ISSUE TITLE
Cannot change color of CartesianChart's ChartLegend

### ISSUE THREAD

**Issue by TimeTravelPenguin** [Live-Charts/Live-Charts#1030]
#### How to reproduce?

The ChartLegend.Background property within the CartecianChart object doesn't change the colour of the Legend fill/background (see image)

My task is that I am exporting the chart to a png, and thus I require either a white or transparent background. Below, in the code, I have a variable called `color` which is correctly a `SolidBrushColor`.

When set to transparent by:
```cs var color = new SolidColorBrush(Colors.Transparent);```
The background is correct and transparent, however, the background of the inner chart legend is not, and remains white,

This is how I am assigning the color:
```cs
var chart = new CartesianChart
{
    // Other code,
    Background = color,
    ChartLegend =
    {
        Background = color
    }
};
```

This is the result of a transparent render (note the image may appear white with Github's white background):
![Image with transparent background](https://user-images.githubusercontent.com/35803538/71303118-65886f80-2408-11ea-8e27-2d503e610676.png)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>.NET Framework 4.7.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10 10.0.18362 Build 18362</td>
</tr>
</table>

**Comment by TimeTravelPenguin** [comment]
Fixed code example

**Comment by kMOsmane** [comment]
I got the same problems, so I tried to create my own legend but it is still not working, any one can help me plz ? 
 customLegend = new DefaultLegend
                {
                    BulletSize = 0,
                    Foreground = seriesColor,
                    Orientation = System.Windows.Controls.Orientation.Horizontal,
                    FontSize = 15,
                    Width = 70,
                    Height = 300,
                    BorderBrush = Brushes.Red,
                    Background = Brushes.Red,
                    IsEnabled = true,
                };
